version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:40"
    timezone: Asia/Tokyo
  versioning-strategy: "lockfile-only"
  open-pull-requests-limit: 10

- package-ecosystem: npm
  directory: "/"
  target-branch: "feature/tldraw-update"
  schedule:
    interval: daily
    time: "13:45"
    timezone: Asia/Tokyo
  versioning-strategy: "increase"
  open-pull-requests-limit: 10
  allow:
    - dependency-name: "tldraw"
