version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "15:58"
    timezone: Asia/Tokyo
  versioning-strategy: "increase"
  open-pull-requests-limit: 10
