version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:35"
    timezone: Asia/Tokyo
  versioning-strategy: "lockfile-only"
  open-pull-requests-limit: 10
